import { useState } from 'react';
import { motion } from 'framer-motion';
import { 
  MdArticle, MdDownload, MdRefresh, MdAutoAwesome, MdCalendarToday, 
  MdSearch, MdCheckCircle, MdTrendingUp, MdArrowForward, MdFileDownload
} from 'react-icons/md';
import toast from 'react-hot-toast';

const REPORT_TEMPLATES = [
  { id: 'rep1', name: 'MERN CRM Pipeline Performance Summary', type: 'Sales Metrics', format: 'CSV / Excel', desc: 'Full breakdown of active deals, conversion rates, and closed won statistics across all teams.' },
  { id: 'rep2', name: 'AI BDA Activity Log & Prompt Auditing', type: 'System Audit', format: 'PDF / HTML', desc: 'Aggregated list of emails, proposals, and objection-handling tasks generated by ManufactoCRM AI.' },
  { id: 'rep3', name: 'SAP / Oracle ERP Synchronization Report', type: 'Integrations', format: 'JSON / XML', desc: 'Uptime records, webhook transaction statistics, and account balance reconciliation statuses.' },
  { id: 'rep4', name: 'Granular Roles & Access Authorization Map', type: 'Security Audit', format: 'CSV', desc: 'Detailed schema mapping every employee role to active dashboard permission scopes.' }
];

const mockGenerated = [
  { id: 'gen1', name: 'Q1_Manufacturing_Sales_Report.csv', size: '2.4 MB', date: '2026-05-20', status: 'Ready' },
  { id: 'gen2', name: 'AI_Assistant_Audit_Log_May.pdf', size: '1.8 MB', date: '2026-05-18', status: 'Ready' },
  { id: 'gen3', name: 'SAP_Webhook_Transactions.json', size: '820 KB', date: '2026-05-15', status: 'Ready' }
];

export default function Reports() {
  const [reports, setReports] = useState(mockGenerated);
  const [selectedTemplate, setSelectedTemplate] = useState('rep1');
  const [loading, setLoading] = useState(false);
  const [dateRange, setDateRange] = useState({ start: '', end: '' });

  const handleGenerate = async (e) => {
    e.preventDefault();
    setLoading(true);
    toast.loading('Compiling database records and formatting report...', { id: 'generating-rep' });
    
    // Simulate generation
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    const template = REPORT_TEMPLATES.find(t => t.id === selectedTemplate);
    const newReport = {
      id: `gen${Date.now()}`,
      name: `${template.name.replace(/\s+/g, '_')}_${new Date().toISOString().slice(0, 10)}.${template.format.split(' ')[0].toLowerCase()}`,
      size: `${(Math.random() * 3 + 0.5).toFixed(1)} MB`,
      date: new Date().toISOString().slice(0, 10),
      status: 'Ready'
    };

    setReports(prev => [newReport, ...prev]);
    setLoading(false);
    toast.success('Report compiled successfully! Download available below.', { id: 'generating-rep', icon: '📊' });
  };

  const handleDownload = (name) => {
    toast.success(`Downloaded ${name} successfully!`, { icon: '📥' });
  };

  const cardStyle = { 
    background: '#ffffff', 
    border: '1px solid rgba(0,0,0,0.06)', 
    borderRadius: 16, 
    padding: 22, 
    boxShadow: '0 2px 8px rgba(0,0,0,0.04)' 
  };

  return (
    <div style={{ padding: '4px 0 24px' }}>
      {/* Header */}
      <motion.div initial={{ opacity: 0, y: -16 }} animate={{ opacity: 1, y: 0 }}
        style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 4 }}>
            <div style={{ width: 36, height: 36, borderRadius: 10, background: 'linear-gradient(135deg,#6366f1,#8b5cf6)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <MdArticle size={20} color="white" />
            </div>
            <h2 style={{ fontSize: 22, fontWeight: 800, color: '#1e293b', letterSpacing: '-0.3px' }}>
              Reports & Document Compiler
            </h2>
          </div>
          <p style={{ fontSize: 13, color: '#64748b', marginLeft: 46 }}>Compile, audit, and download complete enterprise MERN CRM data tables</p>
        </div>
      </motion.div>

      <div style={{ display: 'grid', gridTemplateColumns: '1.3fr 1fr', gap: 16 }}>
        {/* Left Column: Generate Panel */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}
            style={cardStyle}>
            <h3 style={{ fontSize: 15, fontWeight: 800, color: '#1e293b', marginBottom: 16 }}>Compile New Report</h3>
            
            <form onSubmit={handleGenerate} style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
              <div>
                <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: '#64748b', marginBottom: 6 }}>Select Data Template *</label>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                  {REPORT_TEMPLATES.map(t => (
                    <label key={t.id} style={{
                      display: 'flex', gap: 12, padding: '12px 16px', borderRadius: 12, cursor: 'pointer',
                      border: `1.5px solid ${selectedTemplate === t.id ? '#6366f1' : 'rgba(0,0,0,0.06)'}`,
                      background: selectedTemplate === t.id ? '#f5f3ff' : 'transparent',
                      transition: 'all 0.2s'
                    }}>
                      <input type="radio" name="template" checked={selectedTemplate === t.id} onChange={() => setSelectedTemplate(t.id)} style={{ marginTop: 3, accentColor: '#6366f1' }} />
                      <div>
                        <div style={{ fontSize: 13, fontWeight: 700, color: '#1e293b' }}>{t.name}</div>
                        <p style={{ fontSize: 11, color: '#64748b', marginTop: 3, lineHeight: 1.4 }}>{t.desc}</p>
                        <div style={{ display: 'flex', gap: 8, marginTop: 6 }}>
                          <span style={{ fontSize: 10, fontWeight: 700, color: '#6366f1', background: 'rgba(99,102,241,0.1)', padding: '2px 8px', borderRadius: 20 }}>{t.type}</span>
                          <span style={{ fontSize: 10, fontWeight: 700, color: '#10b981', background: 'rgba(16,185,129,0.1)', padding: '2px 8px', borderRadius: 20 }}>{t.format}</span>
                        </div>
                      </div>
                    </label>
                  ))}
                </div>
              </div>

              {/* Date Filters */}
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
                <div>
                  <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: '#64748b', marginBottom: 5 }}>Start Date</label>
                  <input type="date" className="input-dark" value={dateRange.start} onChange={e => setDateRange({ ...dateRange, start: e.target.value })} />
                </div>
                <div>
                  <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: '#64748b', marginBottom: 5 }}>End Date</label>
                  <input type="date" className="input-dark" value={dateRange.end} onChange={e => setDateRange({ ...dateRange, end: e.target.value })} />
                </div>
              </div>

              <button type="submit" disabled={loading} style={{
                marginTop: 6, padding: '12px', background: 'linear-gradient(135deg,#6366f1,#8b5cf6)', border: 'none', borderRadius: 12,
                color: '#fff', fontWeight: 700, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8,
                boxShadow: '0 4px 15px rgba(99,102,241,0.25)', opacity: loading ? 0.8 : 1
              }}>
                {loading ? (
                  <div style={{ width: 18, height: 18, border: '2px solid rgba(255,255,255,0.3)', borderTop: '2px solid #fff', borderRadius: '50%', animation: 'spin 0.6s linear infinite' }} />
                ) : (
                  <><MdAutoAwesome size={16} /> Compile Data Report</>
                )}
              </button>
            </form>
          </motion.div>
        </div>

        {/* Right Column: Download List */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}
            style={cardStyle}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
              <div>
                <h3 style={{ fontSize: 15, fontWeight: 800, color: '#1e293b' }}>Generated Reports</h3>
                <p style={{ fontSize: 11, color: '#94a3b8', marginTop: 2 }}>Ready for local download</p>
              </div>
              <button onClick={() => toast.success('List refreshed!', { icon: '🔄' })} style={{ background: 'rgba(0,0,0,0.03)', border: '1px solid rgba(0,0,0,0.08)', borderRadius: 8, padding: 6, cursor: 'pointer', color: '#64748b' }}>
                <MdRefresh size={16} />
              </button>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              {reports.map((rep) => (
                <div key={rep.id} style={{
                  display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '12px 14px',
                  background: 'rgba(0,0,0,0.015)', border: '1px solid rgba(0,0,0,0.04)', borderRadius: 12
                }}>
                  <div style={{ minWidth: 0, flex: 1, paddingRight: 10 }}>
                    <div style={{ fontSize: 12, fontWeight: 700, color: '#1e293b', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }} title={rep.name}>
                      {rep.name}
                    </div>
                    <div style={{ fontSize: 11, color: '#94a3b8', marginTop: 3 }}>
                      {rep.size} · Compiled {rep.date}
                    </div>
                  </div>
                  <button onClick={() => handleDownload(rep.name)} style={{
                    width: 34, height: 34, borderRadius: 8, border: '1px solid rgba(16,185,129,0.2)',
                    background: 'rgba(16,185,129,0.08)', color: '#10b981', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer'
                  }}>
                    <MdFileDownload size={18} />
                  </button>
                </div>
              ))}
            </div>
          </motion.div>
        </div>
      </div>
      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </div>
  );
}
